const columns = [
  {
    name: 'image-path',
    required: true,
    label: 'Image',
    align: 'center',
    field: (row) => row.imagePath,
    sortable: true,
  },
  {
    name: 'product-name',
    required: true,
    label: 'Product Name',
    align: 'left',
    field: (row) => row.productName,
    sortable: true,
  },
  {
    name: 'price',
    required: true,
    label: 'Price',
    align: 'left',
    field: (row) => row.price,
    sortable: true,
  },
  {
    name: 'discount',
    required: true,
    label: 'Discount',
    align: 'left',
    field: (row) => row.discount,
    sortable: true,
  },
  {
    name: 'quota',
    required: true,
    label: 'Quota',
    align: 'left',
    field: (row) => row.quota,
    sortable: true,
  },
]

const rows_air_conditioner = [
  {
    id: 'lg-hi-wall-9000',
    imagePath: '/products/lg-hi-wall/1.jpg',
    productName: 'Ar condicionado LG HI Wall Split Dual Inverter 9.000 BTUs',
    price: 2156.84,
    discount: 10,
    quota: 12,
    category: 'air_conditioner',
    images: [
      '/products/lg-hi-wall/1.jpg',
      '/products/lg-hi-wall/2.jpg',
      '/products/lg-hi-wall/3.jpg',
    ],
  },
  {
    id: 'split-agratto-9000',
    imagePath: '/products/split-agratto-9000/1.jpg',
    productName:
      'Ar condicionado Split Hi Wall Inverter Agratto Liv 9.000 BTU/h Quente e Frio LCST9QF – 220 Volts',
    price: 1920.0,
    discount: 10,
    quota: 12,
    category: 'air_conditioner',
    images: [
      '/products/split-agratto-9000/1.jpg',
      '/products/split-agratto-9000/2.jpg',
      '/products/split-agratto-9000/3.jpg',
      '/products/split-agratto-9000/4.jpg',
    ],
  },
  {
    id: 'samsung-9000-inverter',
    imagePath: '/products/ar-condicionado-split-samsung-9000/1.webp',
    productName: "Ar-condicionado Split Samsung 9000 BTU's Inverter WindFree AI - AR09DY - 220V",
    price: 3729.9,
    discount: null,
    quota: 12,
    category: 'air_conditioner',
    images: [
      '/products/ar-condicionado-split-samsung-9000/1.webp',
      '/products/ar-condicionado-split-samsung-9000/2.webp',
    ],
  },
  {
    id: 'elgin-9000-eco',
    imagePath: '/products/ar-condicionado-split-elgin-9000/1.webp',
    productName:
      'Ar Condicionado Split Elgin 9000 BTUs Inverter Eco II Connect - HJFE09C2CC - 220V',
    price: 1899.9,
    discount: 13,
    quota: 10,
    category: 'air_conditioner',
    images: [
      '/products/ar-condicionado-split-elgin-9000/1.webp',
      '/products/ar-condicionado-split-elgin-9000/2.webp',
    ],
  },
  {
    id: 'gree-12000-auto',
    imagePath: '/products/ar-condicionado-split-gree-12000/1.webp',
    productName: 'Ar Condicionado Split Gree 12000BTUs Auto Inverter 220V Branco CB574N09200',
    price: 3429.9,
    discount: null,
    quota: 12,
    category: 'air_conditioner',
    images: ['/products/ar-condicionado-split-gree-12000/1.webp'],
  },
  {
    id: 'lg-dual-compact',
    imagePath: '/products/ar-condicionado-split-lg-dual/1.webp',
    productName:
      'Ar-Condicionado Split LG DUAL Inverter Compact +AI 9.000 BTU Frio – S3-Q09AAQAL - 220V',
    price: 2449.9,
    discount: 13,
    quota: 12,
    category: 'air_conditioner',
    images: ['/products/ar-condicionado-split-lg-dual/1.webp'],
  },
]

const rows_fan = [
  {
    id: 'arno-xtreme-6-mesa',
    imagePath: '/products/ventilador-arno-de-mesa-e-parede-40cm-6-pas/1.webp',
    productName: 'Ventilador Arno de Mesa e Parede 40cm 6 Pás X-TREME 6 140W 220V Preto - VE60',
    price: 299.9,
    discount: 34,
    quota: 10,
    category: 'fan',
    images: ['/products/ventilador-arno-de-mesa-e-parede-40cm-6-pas/1.webp'],
  },
  {
    id: 'arno-xtreme-7-mesa',
    imagePath: 'products/ventilador-arno-x-treme-7-mesa-3-velocidades-40cm-preto-220v-ve70/1.webp',
    productName: 'Ventilador Arno X-treme 7 Mesa 3 Velocidades 40cm Preto 220V - VE70',
    price: 299.9,
    discount: 5,
    quota: 10,
    category: 'fan',
    images: ['products/ventilador-arno-x-treme-7-mesa-3-velocidades-40cm-preto-220v-ve70/1.webp'],
  },
  {
    id: 'britania-maxx-force',
    imagePath: '/products/ventilador-britania-2-em-1-maxx-force-150w-40cm-127v-bvt400/1.webp',
    productName: 'Ventilador Britânia 2 em 1 Maxx Force 150W 40cm 127V - BVT400',
    price: 249.9,
    discount: 20,
    quota: 10,
    category: 'fan',
    images: ['/products/ventilador-britania-2-em-1-maxx-force-150w-40cm-127v-bvt400/1.webp'],
  },
  {
    id: 'mondial-mesa-3-vel',
    imagePath: '/products/ventilador-de-mesa-3-velocidades-220V/1.webp',
    productName: 'Ventilador de Mesa 3 Velocidades 220V VSP30W Branco - Mondial',
    price: 127.9,
    discount: 13,
    quota: 10,
    category: 'fan',
    images: ['/products/ventilador-de-mesa-3-velocidades-220V/1.webp'],
  },
  {
    id: 'cadence-mesa-40cm',
    imagePath:
      '/products/ventilador-de-mesa-cadence-3-velocidades-40cm-140w-preto-220v-vtr410/1.webp',
    productName: 'Ventilador de Mesa Cadence 3 Velocidades 40cm 140W Preto 220V - VTR410',
    price: 159.9,
    discount: null,
    quota: 10,
    category: 'fan',
    images: [
      '/products/ventilador-de-mesa-cadence-3-velocidades-40cm-140w-preto-220v-vtr410/1.webp',
    ],
  },
  {
    id: 'mondial-50cm-3-vel',
    imagePath: '/products/ventilador-de-mesa-mondial-50cm-com-3-velocidades/1.webp',
    productName: 'Ventilador de Mesa Mondial 50cm com 3 Velocidades 220V VTX-50-8P',
    price: 219.9,
    discount: 13,
    quota: 10,
    category: 'fan',
    images: ['/products/ventilador-de-mesa-mondial-50cm-com-3-velocidades/1.webp'],
  },
]

export { columns, rows_air_conditioner, rows_fan }
